#!/bin/sh
set -eu

: "${RABBITMQ_USER:?RABBITMQ_USER is required}"
: "${RABBITMQ_PASSWORD_FILE:?RABBITMQ_PASSWORD_FILE is required}"

SEED_USERNAME="$RABBITMQ_USER"
SEED_USER_PASSWORD="$(cat "$RABBITMQ_PASSWORD_FILE")"
export SEED_USERNAME SEED_USER_PASSWORD
unset RABBITMQ_PASSWORD_FILE

exec docker-entrypoint.sh "$@"
